name: orbitsync

packages:
  - packages/**
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "dart analyze ."
    description: Analyze all Dart packages.
  format:
    run: dart format --set-exit-if-changed packages examples
    description: Check Dart formatting.
  test:
    run: melos exec --dir-exists=test -- "dart test"
    description: Run package unit tests.
  server:test:
    run: npm test --prefix server_mock
    description: Run mock server tests.
